[acoustics]
sr = 16000
n_fft = 512
win_length = 512
hop_length = 256


[inferencer]
path = "inferencer.Inferencer"
type = "full_band_crm_mask"

[inferencer.args]
n_neighbor = 15


# [dataset]
# path = "dataset_inference.Dataset"
# [dataset.args]
# dataset_dir_list = [
#     "/home/shkarupa/Documents/It-Jim/speech_enhancement/output/noisy_test"
# ]
# sr = 16000

[dataset]
path = "dataset_custom.CustomDataset"
[dataset.args]
stage = "inference"
clean_dir = "/home/shkarupa/Documents/It-Jim/speech_enhancement/speech_and_noise_dataset/clean_test"
noise_dir = "/home/shkarupa/Documents/It-Jim/speech_enhancement/speech_and_noise_dataset/noise_test"
num_workers = 4
preload_clean = false
preload_noise = false
fixed_noise_scale = false
noise_scale = 2.3
snr_range = [-5, 20]
sr = 16000
offset = 0.5
# duration = 1.24
target_dbfs = -25
dbfs_range = 20
fix_dbfs = true
cleaned_dir = "/home/shkarupa/Documents/It-Jim/speech_enhancement/output/inference_custom/cleaned"


[model]
path = "model.Model"

[model.args]
num_freqs = 257
look_ahead = 2
sequence_model = "LSTM"
fb_num_neighbors = 0
sb_num_neighbors = 15
fb_output_activate_function = "ReLU"
sb_output_activate_function = false
fb_model_hidden_size = 512
sb_model_hidden_size = 384
weight_init = false
norm_type = "offline_laplace_norm"
num_groups_in_drop_band = 2

